### PR TITLE
Added a map to cache uniform locations

### PR DESCRIPTION
**Pull request by jorisdejong**
Tbh I'm not sure if this is safe to do like this or even if it's actually any faster, but it was a nice exercise anyway

### CODE REVIEW

**Comment by jorisdejong** [comment]
Fixes #80

**Comment by MennoVink** [comment]
Using a lookup like this is not the best way to go about it. The intended way to use the uniform locations is to query them once after you've loaded the shader and then keep reusing them during the entire program. A lookup like this is suboptimal because it uses the heap, needs to hash the string and do a search through the map. On top of that this implementation is suboptimal in the common case where the location is already stored. It does the heap alloc/dealloc twice, the hashing twice and the lookup twice. It would already be better if it uses the find function and possibly an unordered_map, but yeah i'd be more inclined to just close the issue. It doesn't help achieve maximum performance nor does it make anything easier, what do you think?

**Comment by jorisdejong** [comment]
Yeah, I agree. The Shader class exists to make things easier, if you want to achieve maximum performance you can always write straight OpenGL. For future proofing, it'd be nice if the API would completely hide all OpenGL specific calls though, but I don't know enough about Vulkan/Metal/what have you to say anything relevant about that.

Just for my own learning, this would be an implementation that doesn't do everything twice?
`auto it = uniformLocations.find( name );
if ( it == uniformLocations.end() )
{
   GLint location = glGetUniformLocation( programID, name );
   uniformLocations[ name ] = location;
   return location;
} 
else
 return it->second;'

**Comment by MennoVink** [comment]
We have no plans to turn ffgl into a cross-api plugin framework so api abstraction is not a thing.
And yes, that setup does the slow parts once where you make the find call, from there it returns the value by reading from the iterator.

**Pull request closed without merging**
