### PR TITLE
FFGL 2.0

### PR DESCRIPTION
**Pull request by ResolumeMenno**
Updated the FFGL sdk to enable development of plugins that will run in a new host supporting OpenGL 4.1 and no longer supporting the old FreeFrame CPU processing.

### CODE REVIEW

**Comment by rsodre** [comment]
Will old hosts be compatible with plugins built with this FFGL 2.0?

Is there any specs on FFGL 2.0?

**Comment by ResolumeMenno** [comment]
Hello Roger,

No, old hosts will not be able to load plugins developed with the FFGL 2.0
sdk.
We've removed the old FreeFrame functionality (the cpu processing parts)
and the easiest way of communicating lack of that functionality in the
plugin to the host was by failing initialisation of the plugin on old
hosts. New hosts will use a new initialise call which then lets the plugin
know that it's okay not to support the old functionality.
Additionally, hosts may make a choice to impose additional requirements or
relax some of the requirements used for FFGL 1.6 plugins. If a host relaxes
some of the requirements that will lead to plugins being developed which
cannot run in old hosts anyway because it doesn't support the new
functionality.
For example, Resolume requires 2.0 plugins to be compatible with an OpenGL
4.1 Core Context. A plugin that is then updated to use OpenGL 4.1
functionality cannot run in an old Resolume host because a previous
Resolume doesn't support OpenGL 4.1.

As far as the specs are concerned we have the old specs for FFGL 1.5 but
these havn't been updated for a while so changes for 1.6 and 2.0 aren't in
there. Which side of the specs are you interested in? The host side or the
plugin side?

Kind Regards,
Menno

**Comment by rsodre** [comment]
Which version of Resolume will start supporting FFGL 2.0?
It's not clear to me if Resolume will keep accepting FFGL 1.5/1.6 plugins.

I'm just curious about the specs. As a developer, I just want to understand capabilities and if it can be useful to me in some way.

**Comment by ResolumeMenno** [comment]
We havn't decided yet in which Resolume version we will be adopting FFGL
2.0, lets call it 6.1.3 for now.
In that version, Resolume will no longer support FFGL 1.5/1.6.

**Pull request merged**
